### ISSUE TITLE
Hovering make the other titles disappear

### ISSUE THREAD

**Issue by ddnexus** [nlpsuge/Always-Show-Titles-In-Overview#1]
When you hover over one window, the other titles disappear. That happens especially when you switch desktop: if your cursor happens to land on a window instead of an empty space, you never see the titles of the other windows.
(Ubuntu 18.10 up-to-date)

**Comment by nlpsuge** [comment]
@ddnexus Hi, I'm not using Ubuntu, what's the version of gnome-shell?

**Comment by ddnexus** [comment]
GNOME Shell 3.30.2

**Comment by nlpsuge** [comment]
@ddnexus Downloading Ubuntu 18.10, I'll address this issue. Sorry for the delay.

**Comment by nlpsuge** [comment]
@ddnexus You can use this release:
https://github.com/nlpsuge/Always-Show-Titles-In-Overview/releases/tag/v0.1. This one should work wih GNOME Shell 3.30.2

**Comment by ddnexus** [comment]
Thank you @nlpsuge! I am just about to upgrade to Ubuntu 19.10. I hope it will work also with that shell (3.32).

**Comment by nlpsuge** [comment]
@ddnexus I'm using Gnome Shell 3.32, the latest version at https://extensions.gnome.org/extension/1689/always-show-titles-in-overview/ should work. It's a bit flawed. I'll take time to optimize it.

**Comment by ddnexus** [comment]
It works! Thank you!!!!
