### ISSUE TITLE
Gnome 42?

### ISSUE THREAD

**Issue by vess-dev** [nlpsuge/Always-Show-Titles-In-Overview#12]
Title. Thank you for all that you do <3

**Comment by nlpsuge** [comment]
OK. I'll upgrade it to Gnome 42 later today. :)

**Comment by nlpsuge** [comment]
The latest release on the [E.G.O](https://extensions.gnome.org/extension/1689/always-show-titles-in-overview/) has already supported the Gnome 42. :)
