### ISSUE TITLE
[Feature request] App title position (Bottom, Center)

### ISSUE THREAD

**Issue by hamiller** [nlpsuge/Always-Show-Titles-In-Overview#13]
Can you please add the possibility to also vertically center the title of the programs (in the overview)?
Like you already provide for the icons...

Would be awesome!

**Comment by nlpsuge** [comment]
OK. Please note that I'm busy recently, I'll add this feature ASAP.

**Comment by nlpsuge** [comment]
finished by #14, push to E.G.O later.
