### ISSUE TITLE
Support for Gnome 45

### ISSUE THREAD

**Issue by mbeps** [nlpsuge/Always-Show-Titles-In-Overview#17]
This extension needs to be updated to work with Gnome 45. Most extensions are broken due the new standard.

**Comment by friimaind** [comment]
It would be great! :pray:

**Comment by nlpsuge** [comment]
Hi,

The default branch has switched to gnome-45+, which supports gnome 45 already. I should be able to release a new version that supports Gnome 45 to https://extensions.gnome.org/ this week.

**Comment by nlpsuge** [comment]
@friimaind @mbeps Done.

A new version that supports Gnome 45 has been approved on https://extensions.gnome.org. You might have received the update notification.
