### ISSUE TITLE
Gnome 40 compatibility

### ISSUE THREAD

**Issue by epizut** [nlpsuge/Always-Show-Titles-In-Overview#3]
Thank you for your work on this. I share your concern about Jetbrains IDEs.

Did you plan to support Gnome 40?

**Comment by nlpsuge** [comment]
Sure. I'm on vacation recently. I will port this extension to Gnome 40.

**Comment by nlpsuge** [comment]
@epizut 

Hi,
I've port this extension to Gnome 40 and upload it to https://extensions.gnome.org/extension/1689/always-show-titles-in-overview/, you should receive the update notification in a few days.

**Comment by nlpsuge** [comment]
@epizut 
Hi,
The 40 version extension has been approved, you can update now.

**Comment by epizut** [comment]
It works like (py)charm. Thanks a lot.
