### ISSUE TITLE
Error loading extension

### ISSUE THREAD

**Issue by pesader** [nlpsuge/Always-Show-Titles-In-Overview#4]
Hi. First of all, thanks for developing this extension!

I was eager to try it out, but I haven't been able to get it working. Installing it either via the Gnome Shell Extensions [website](https://extensions.gnome.org/extension/1689/always-show-titles-in-overview/) or manually (downloading the extension version 8 for gnome-shell 3.36) have both led to this:

![](https://i.imgur.com/edo3nfP.png)
When I hover over my cursor over this exclamation mark I get the message "Error loading extension".

I dug a little deeper into the logs and this is what I found:
```log
May 22 23:13:55 surface-linux gnome-shell[3845]: JS ERROR: Extension Always-Show-Titles-In-Overview@gmail.com: ImportError: No JS module 'windowPreview' found in search path
    @/home/pesader/.local/share/gnome-shell/extensions/Always-Show-Titles-In-Overview@gmail.com/extension.js:14:23
May 23 10:54:09 surface-linux gnome-shell[3836]: JS ERROR: Extension Always-Show-Titles-In-Overview@gmail.com: ImportError: No JS module 'windowPreview' found in search path
    @/home/pesader/.local/share/gnome-shell/extensions/Always-Show-Titles-In-Overview@gmail.com/extension.js:14:23
```   

Additional info:
gnome-shell: 3.36.7
distro: ubuntu 20.04

Thanks again for developing this!

**Comment by nlpsuge** [comment]
Hi,

Please download this release https://github.com/nlpsuge/Always-Show-Titles-In-Overview/releases/tag/v3.36.1. Unzip it and copy its files to ~/.local/share/gnome-shell/extensions/Always-Show-Titles-In-Overview@gmail.com/ and override existing files.

Or run those command lines:
$ wget https://github.com/nlpsuge/Always-Show-Titles-In-Overview/archive/refs/tags/v3.36.1.zip
$ unzip v3.36.1.zip
$ cp -r Always-Show-Titles-In-Overview-3.36.1/* ~/.local/share/gnome-shell/extensions/Always-Show-Titles-In-Overview@gmail.com/

Then type `r` in the dialog of `ALT+F2`, waiting for the rebooting of Gnome desktop. 

Please use `killall -3 gnome-shell` under root to reboot Gnome desktop once your desktop is frozen (but this should not happen). 

Please note that v3.36.1 is the last version that supports Gnome 3.36.x.

------
I've missing something...

The extension version 8 for gnome-shell 3.36 is not right... The version 5 for gnome-shell 3.36 should work. Sorry for that. :(

**Comment by nlpsuge** [comment]
I've inactivated version 8 which should only support 3.38 but not 3.36. Version 5 should work on Gnome 3.36, if not please let me know. 
I've uploaded version 10 which only support Gnome 3.38 and not effect Gnome 40.

Hope this can fix my mistakes.

**Comment by pesader** [comment]
Hey, sorry for the late reply.

I have been using the extension the last few days and it is working flawlessly now! It provided a drastic workflow improvement for me, so I'm very grateful :)

Great work!
