### ISSUE TITLE
Overview can't be closed when started on 2nd screen

### ISSUE THREAD

**Issue by herrminni** [nlpsuge/Always-Show-Titles-In-Overview#8]
With the latest version on extensions.gnome.org, the overview can't be closed any more by pressing ESC or SUPER key.
I found, that this only happens when the overview is started on the 2nd screen (e.g. by pressing SUPER).

Current versions:
- Extension "Always-Show-Titles-In-Overview@gmail.com" 17
- GNOME Shell 40.5
- Ubuntu 21.10

**Comment by nlpsuge** [comment]
Hi,

Please run this command before reproduce this issue:
```sh
journalctl /usr/bin/gnome-shell -f
```
You should be able to restore the Gnome-Shell by running `Alt + F2 -> r` if you are using Gnome on X.org.

Can you see any errors or logs related to this issue? if so please paste them.

**Comment by herrminni** [comment]
Hi nlpsuge,

sure, I could have thought about looking into the syslog/journal myself! ;-)

I just simulated the problem again, all other extensions are disabled, except the UserThemes.

The exception is:
`
JS ERROR: TypeError: windowPreview._workspace.metaWorkspace is null
_animateFromOverview@/home/minni/.local/share/gnome-shell/extensions/Always-Show-Titles-In-Overview@gmail.com/workspace.js:26:9
enable/<@/home/minni/.local/share/gnome-shell/extensions/Always-Show-Titles-In-Overview@gmail.com/workspace.js:60:37
injectOrOverrideFunction/objectPrototype[functionName]@/home/minni/.local/share/gnome-shell/extensions/Always-Show-Titles-In-Overview@gmail.com/utils/objectPrototype.js:19:54
prepareToLeaveOverview@resource:///org/gnome/shell/ui/workspacesView.js:588:25
prepareToLeaveOverview@resource:///org/gnome/shell/ui/workspacesView.js:818:30
prepareToLeaveOverview@resource:///org/gnome/shell/ui/workspacesView.js:1053:38
animateFromOverview@resource:///org/gnome/shell/ui/overviewControls.js:703:33
animateFromOverview@resource:///org/gnome/shell/ui/overview.js:97:24
_animateNotVisible@resource:///org/gnome/shell/ui/overview.js:605:24
hide@resource:///org/gnome/shell/ui/overview.js:594:14
toggle@resource:///org/gnome/shell/ui/overview.js:642:18
_init/<@resource:///org/gnome/shell/ui/overviewControls.js:435:31
`

Reloading/restoring the gnome-shell with "r" did not work.
The shell restarts, but the overview is opened directly after the restart and can't be closed with ESC / SUPER.

If you need anything else or want me to test a possible fix, just drop me a line here!
Thank you for looking into it!

Best regards,
Michael

**Comment by nlpsuge** [comment]
> The shell restarts, but the overview is opened directly after the restart and can't be closed with ESC / SUPER.

Please install https://extensions.gnome.org/extension/4099/no-overview/ if this issue annoy you too much :)

**Comment by nlpsuge** [comment]
Hi Michael,
I pushed a fix to branch `fixbug-failed-leave-overview-on-2nd-monitor`, see https://github.com/nlpsuge/Always-Show-Titles-In-Overview/commit/c51a61c7276c99a577660b79f248aa4373b2e8b6 for more details.

I saw you commit a fix too. 

These two fixes are a little different, I'm not sure which one is better, I don't have a second monitor to test.

Please see [the gnome-shell source workspace.js](https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/gnome-41/js/ui/workspace.js#L1379). It seems that if `this.metaWorkspace` is null, then this workspace is the active one (the current one).
